obstack.h is not present on musl
In cronie 1.5.5, there is enabled anacron by default.
However, it fails due to:

anacron/readtab.c:33:10: fatal error: obstack.h: No such file or directory
 #include <obstack.h>